### ISSUE TITLE
ERROR10 - Menu se queda pegado

### ISSUE THREAD

**Issue by jagos97** [Proyectos1-FDI-UCM/c1920-Grupo01#10]
Descripción
Al comenzar el juego, si le doy click al botón izquierdo, antes que nada, se queda pegado el juego y tengo que salirme del juego para comenzar otra vez.

Pasos
1.	Iniciar el juego
2.	Dale click izquierdo

**Comment by sergimol** [comment]
Esto no es ningún error, aunque no aparezca ningún botón como seleccionado se puede hacer click en cualquiera de ellos.
