### ISSUE TITLE
ERROR12 - No se puede regresar al principio

### ISSUE THREAD

**Issue by jagos97** [Proyectos1-FDI-UCM/c1920-Grupo01#12]
Descripción

Al pasar la última escena, las escaleras no regresan a la primera escena 

Pasos

1.	Pasar la última escena 
2.	Pasar por las escaleras 

Captura de pantalla o vídeo
https://youtu.be/zlzCwvmleUM

**Comment by SergioJAlfonso** [comment]
En el juego final ninguna escalera permite regresar a escenas anteriores, así que no supone ningún problema
