### ISSUE TITLE
ERROR 4 - Fallo del color rojo (invencibilidad)

### ISSUE THREAD

**Issue by rubenglezortiz** [Proyectos1-FDI-UCM/c1920-Grupo01#4]
### Descripción

Cuando tienes la invulnerabilidad activada e intentas conseguir el rebote (morado) a veces, cuando bloqueas la bala morada, mueres, sin funcionar la invencibilidad o el bloqueo.

### Pasos 

1. Conseguir el color rojo.
2. Con él, ir a intentar conseguir el morado.
3. No he conseguido reproducir el error siempre, el timing es difícil de calcular, pero adjunto un vídeo donde se puede observar el fallo.

### Captura de pantalla o vídeo
https://www.youtube.com/watch?v=4yxp0jzr5cc&feature=youtu.be

**Comment by SergioJAlfonso** [comment]
Por mucho que lo hemos intentado reproducir no lo hemos conseguido, así que probablemente se trate de un error de la build de pruebas.
